# Generated by Django 3.2.8 on 2021-11-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product1',
        ),
    ]
