# Generated by Django 3.2.8 on 2021-11-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_Id',
            new_name='cart_id',
        ),
    ]
